//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fly
    {
        public int Id { get; set; }
        public int Company_id { get; set; }
        public bool type { get; set; }
        public System.DateTime late { get; set; }
        public int Gate_id { get; set; }
        public int runway_id { get; set; }
        public System.DateTime Date { get; set; }
        public int City_id { get; set; }
        public int Airportid { get; set; }
        public string No { get; set; }
        public int Status { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Gate Gate { get; set; }
        public virtual Runway Runway { get; set; }
    }
}
